In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
import seaborn as sns
from tqdm import tqdm, tqdm_pandas
import re
from collections import Counter
from emoji import core

In [2]:
df_com = pd.read_csv('./data/댓글.csv')
df_com

,comment,title,text_number,topic,year,month,yyyy,mm
0,저 하구 있는데 괜찮다라구요\n아이도 재미있어 해요,⚘밀크* 수업 하시는분 계실까요?,5736700,초등 밀크티,2022,2,2022,2
1,"아, 그렇군요 ㅎ 무료체험 이것저것 해봤는데 솔직히 비교가 잘 안되네요 ㅠ 일단 아...",⚘밀크* 수업 하시는분 계실까요?,5736700,초등 밀크티,2022,2,2022,2
2,저희도 체험하고 나서 지금 하고 있어요. 각자마다 장단점 있는거 같아요. 아이가 좋...,⚘밀크* 수업 하시는분 계실까요?,5736700,초등 밀크티,2022,2,2022,2
3,"아, 그렇군요 저도 지금 알아보고 있는데 탭만 받아서 하다보니 골고루 활용을 잘 못...",⚘밀크* 수업 하시는분 계실까요?,5736700,초등 밀크티,2022,2,2022,2
4,저희애둘 일년째하고있어요~ 둘다알아서들잘해요~^^\n저두 만족하고있구요~~^^,⚘밀크* 수업 하시는분 계실까요?,5736700,초등 밀크티,2022,2,2022,2
...,...,...,...,...,...,...,...,...
5277,저학년이 아니라서요ㅠㅠ,기타과목 잘 되어 있는 초등 학습지,5842178,초등 밀크티,2022,5,2022,5
5278,저희아이도 ㅇㅋ패드학습지로 공부시작햇는데 영상보고 퀴즈풀면서 잘 학주더라구요~지면학...,기타과목 잘 되어 있는 초등 학습지,5842178,초등 밀크티,2022,5,2022,5
5279,초3이면 빨간펜 아이캔두 추천드려요 검정교과서라 출판사별 선택해서 학습가능해요,기타과목 잘 되어 있는 초등 학습지,5842178,초등 밀크티,2022,5,2022,5
5280,비교과목까지 생각하면 밀크티요~ 코딩 논술 한자 중국어 다양해요 애들 눈높이에 맞춰...,기타과목 잘 되어 있는 초등 학습지,5842178,초등 밀크티,2022,5,2022,5
5281,채팅드릴게요~~^^,기타과목 잘 되어 있는 초등 학습지,5842178,초등 밀크티,2022,5,2022,5

In [3]:
df_main = pd.read_csv('./data/본문.csv')
df_main

,title,date,click,text,text_number,topic,year,month,yyyy,mm
0,아이 교육 질문 드려요,2022-04-14 20:41:00.000,275,안녕하세요~\n초등학생 아이 학원 다니고 있는데 학원을 하나 더 보내자니 힘들어 할...,6987657,초등 밀크티,2022,4,2022,4
1,애 공부때문에 한숨 나와요..,2022-04-12 20:47:00.000,2052,제가 무슨 전담 과외선생도 아니고\n언제까지 제가 알려주고 떠먹여줘야 되는지\n궁금...,6985609,초등 밀크티,2022,4,2022,4
2,밀크티 or 와이즈캠프,2022-04-05 08:09:00.000,305,"무료체험중인데,\n둘다 비슷한거 같아요ㅎㅎㅎ 결정장애ㅠ\n저는 와이즈캠프. 아이는 ...",6978355,초등 밀크티,2022,4,2022,4
3,초등 저학년 학원요,2022-04-03 16:22:00.000,436,초2 여아인데요. 굉장히 귀찮음쟁이에요. 학원도 다니기 싫어하고 집에서 엄마랑 같이...,6976983,초등 밀크티,2022,4,2022,4
4,패드학습지도움되나요?,2022-06-16 08:41:00.000,533,"웅x 스마트올 체험햇는데 갤럭시탭 옛날거라서 부팅이 너무 느리더라구요, 그래서 애가...",7042708,초등 밀크티,2022,6,2022,6
...,...,...,...,...,...,...,...,...,...,...
348,사교육에대한생각,2022-01-21 09:26:00.000,1332,저는 8살 5살 아들을 키우고있는엄마예요.\n저는 지금까지 애들 사교육도 시켜본적없...,4248343,초등 밀크티,2022,1,2022,1
349,밀크티 체험해보고 싶은데,2022-01-20 12:55:00.000,230,이번에 초등학교 들어가는 아이가 있는데\n밀크티 체험해보고 싶어서요.\n밀크티 하고...,4247785,초등 밀크티,2022,1,2022,1
350,올해 7세 학습지,2022-01-19 09:34:00.000,275,지금까진 아무것도 안했는데\n내년에 초등학교 간다생각하니\n이제 뭐라도 시켜야 할것...,4246873,초등 밀크티,2022,1,2022,1
351,윙x 밀크x,2022-01-18 22:30:00.000,424,올해 6살 ( 아직 아무것도 몰음)\n초등 2학년 ㅠ\n집에서 문제집 푸는정도 에요...,4246720,초등 밀크티,2022,1,2022,1
352,밀크* 무료체험 해보고싶은데 도와주세요~~,2022-01-05 17:00:00.000,172,초등학생 애들 밀크* 무료체험 해보고싶은데\n영사님 통해서 하는거랑 지인추천 받고하...,4237846,초등 밀크티,2022,1,2022,1

In [4]:
df_1 = df_com.drop(['text_number','year','month'], axis=1)
df_1['etc'] = '본문'
df_2 = df_main.drop(['date','click','text_number','year','month'], axis=1)
df_2['etc'] = '댓글'
df_1.rename(columns={'comment' : 'text'}, inplace=True)
df = pd.concat([df_1,df_2])
df.sort_values('title')
df.reset_index(drop=True, inplace=True)
df.drop_duplicates(['text'])
df

,text,title,topic,yyyy,mm,etc
0,저 하구 있는데 괜찮다라구요\n아이도 재미있어 해요,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
1,"아, 그렇군요 ㅎ 무료체험 이것저것 해봤는데 솔직히 비교가 잘 안되네요 ㅠ 일단 아...",⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
2,저희도 체험하고 나서 지금 하고 있어요. 각자마다 장단점 있는거 같아요. 아이가 좋...,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
3,"아, 그렇군요 저도 지금 알아보고 있는데 탭만 받아서 하다보니 골고루 활용을 잘 못...",⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
4,저희애둘 일년째하고있어요~ 둘다알아서들잘해요~^^\n저두 만족하고있구요~~^^,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
...,...,...,...,...,...,...
5630,저는 8살 5살 아들을 키우고있는엄마예요.\n저는 지금까지 애들 사교육도 시켜본적없...,사교육에대한생각,초등 밀크티,2022,1,댓글
5631,이번에 초등학교 들어가는 아이가 있는데\n밀크티 체험해보고 싶어서요.\n밀크티 하고...,밀크티 체험해보고 싶은데,초등 밀크티,2022,1,댓글
5632,지금까진 아무것도 안했는데\n내년에 초등학교 간다생각하니\n이제 뭐라도 시켜야 할것...,올해 7세 학습지,초등 밀크티,2022,1,댓글
5633,올해 6살 ( 아직 아무것도 몰음)\n초등 2학년 ㅠ\n집에서 문제집 푸는정도 에요...,윙x 밀크x,초등 밀크티,2022,1,댓글
5634,초등학생 애들 밀크* 무료체험 해보고싶은데\n영사님 통해서 하는거랑 지인추천 받고하...,밀크* 무료체험 해보고싶은데 도와주세요~~,초등 밀크티,2022,1,댓글

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5635 entries, 0 to 5634
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    5625 non-null   object
 1   title   5635 non-null   object
 2   topic   5635 non-null   object
 3   yyyy    5635 non-null   int64
 4   mm      5635 non-null   int64
 5   etc     5635 non-null   object
dtypes: int64(2), object(4)
memory usage: 264.3+ KB

In [6]:
df.fillna('no sentence', inplace=True)

In [7]:
df.isnull().sum()

text     0
title    0
topic    0
yyyy     0
mm       0
etc      0
dtype: int64

In [8]:
# 태그 제거
def del_tag_check(text):
    text = re.sub('http:', '', text)
    text = re.sub('comhttpsm.', '', text)
    text = re.sub(r'(\d{2,4})-(\d{3,4})-?(\d{0,4})?', '', text) # 전화번호 제거
    text = re.sub('blog.', '', text)
    text = re.sub('naver.', '', text)
    text = re.sub('co. kr', '', text)

    return text

df['text'] = df['text'].apply(lambda x : del_tag_check(x))

In [9]:
# 문자 통일

# 영어 소문자화
df['text'] = df['text'].apply(lambda x: x.lower())

# 같은 의미를 담은 문자
def combine_check(contents):

    # 밀크티
    contents = re.sub('ㅁㅋ', '밀크', contents)
    contents = re.sub('밀ㅋ', '밀크', contents)
    contents = re.sub('ㅁ크', '밀크', contents)
    
    contents = re.sub('밀크t', '밀크티', contents) #영어를 모두 소문자화 했으므로 대문자T는 진행 X
    contents = re.sub('milkt', '밀크티', contents)
    contents = re.sub('milk티', '밀크티', contents)

    contents = re.sub('밀크[*]', '밀크티', contents)
    contents = re.sub('밀[*]티', '밀크티', contents)
    contents = re.sub('[*]크티', '밀크티', contents)
    contents = re.sub('밀[*][*]', '밀크티', contents)
    contents = re.sub('[*][*]티', '밀크티', contents)
    contents = re.sub('[*]크[*]', '밀크티', contents)

    contents = re.sub('밀크o','밀크티',contents)
    contents = re.sub('밀o티','밀크티',contents)
    contents = re.sub('o크티','밀크티',contents)
    contents = re.sub('밀oo','밀크티',contents)
    contents = re.sub('oo티','밀크티',contents)
    contents = re.sub('o크o','밀크티',contents)

    contents = re.sub('밀크0','밀크티',contents)
    contents = re.sub('밀0티','밀크티',contents)
    contents = re.sub('0크티','밀크티',contents)
    contents = re.sub('밀00','밀크티',contents)
    contents = re.sub('00티','밀크티',contents)
    contents = re.sub('0크0','밀크티',contents)

    contents = re.sub('ㅁㅋㅌ', '밀크티', contents)
    contents = re.sub('ㅁ크ㅌ', '밀크티', contents)
    contents = re.sub('밀크ㅌ', '밀크티', contents)
    contents = re.sub('밀ㅋ티', '밀크티', contents)
    
    contents = re.sub('밀크@', '밀크티', contents)
    contents = re.sub('밀@티', '밀크티', contents)
    contents = re.sub('@크티', '밀크티', contents)
    contents = re.sub('밀@@', '밀크티', contents)
    contents = re.sub('@크@', '밀크티', contents)
    contents = re.sub('@@티', '밀크티', contents)
    # contents = re.sub('밀', '밀크티', contents)
    # contents = re.sub('크', '밀크티', contents)
    # contents = re.sub('티', '밀크티', contents)

    # 홈런
    contents = re.sub('홈@', '홈런', contents)
    contents = re.sub('@런', '홈런', contents)
    # contents = re.sub('홈', '홈런', contents)
    # contents = re.sub('런', '홈런', contents)

    contents = re.sub('홈[*]', '홈런', contents)
    contents = re.sub('[*]런', '홈런', contents)

    contents = re.sub('홈o', '홈런', contents)
    contents = re.sub('o런', '홈런', contents)

    contents = re.sub('홈0', '홈런', contents)
    contents = re.sub('0런', '홈런', contents)

    contents = re.sub('ㅎㄹ', '홈런', contents)
    contents = re.sub('ㅎ런', '홈런', contents)
    contents = re.sub('홈ㄹ', '홈런', contents)

    contents = re.sub('아이스크림 홈런', '홈런', contents)
    contents = re.sub('아이스크림 에듀 홈런', '홈런', contents)

    contents = re.sub('ㅇㅇㅅㅋㄹ 홈런', '홈런', contents)
    contents = re.sub('ㅇㅇㅅㅋㄹ ㅇㄷ 홈런', '홈런', contents)    # +....


    # 윙크
    contents = re.sub('윙@', '윙크', contents)
    contents = re.sub('@크', '윙크', contents)

    contents = re.sub('윙[*]', '윙크', contents)
    contents = re.sub('[*]크', '윙크', contents)

    contents = re.sub('윙o', '윙크', contents)
    contents = re.sub('o크', '윙크', contents)

    contents = re.sub('윙0', '윙크', contents)
    contents = re.sub('0크', '윙크', contents)

    contents = re.sub('ㅇㅋ', '윙크', contents)
    contents = re.sub('ㅇ크', '윙크', contents)
    contents = re.sub('윙ㅋ', '윙크', contents)


    # 웅진 스마트올



    # 엘리하이



    # 명사
    contents = re.sub('할미','할머니', contents)
    contents = re.sub('티비','텔레비전', contents)
    # contents = re.sub('','', contents)
    # contents = re.sub('','', contents)
    # contents = re.sub('','', contents)

    # contents = re.sub('','', contents)

    return contents

In [10]:
contents = '밀0티'

contents = re.sub('밀0티','밀크티',contents)
contents

'밀크티'

In [13]:
print(df['text'][111])
df['text'] = df['text'].apply(lambda x : combine_check(x))
print(df['text'][111])

체험을 몇곳 해보세요
전 윙ㅋ 하는중 밀ㅋ 체험했는데.. 패드야 다 좋아하니..
밀크가 매월교재가 없다고 해서 윙ㅋ 재연장요
체험을 몇곳 해보세요
전 윙크 하는중 밀ㅋ 체험했는데.. 패드야 다 좋아하니..
밀크가 매월교재가 없다고 해서 윙크 재연장요

In [12]:
print(df['text'][111])

체험을 몇곳 해보세요
전 윙ㅋ 하는중 밀ㅋ 체험했는데.. 패드야 다 좋아하니..
밀크가 매월교재가 없다고 해서 윙ㅋ 재연장요

In [49]:
# 특수문자 제거

display(df.text[0])
# 특수 기호 제거
df.text = df.text.apply(lambda x : re.sub('[-=+,#/\?:^$@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》\n★▲;]',' ', x))

# '\E' 모양 제거
df.text = df.text.apply(lambda x : re.sub('[\a-zA-Z]. ',' ',x))

# 이모티콘 제거
df.text = df.text.apply(lambda x : core.replace_emoji(x, replace=''))

# # 자음만 적힌 경우 제거
# df.text = df.text.apply(lambda x : re.sub('[ㄱ-ㅎ]+', '', x))

display(df.head())
display(df.text[0])

'저 하구 있는데 괜찮다라구요\n아이도 재미있어 해요'

,text,title,topic,yyyy,mm,etc
0,저 하구 있는데 괜찮다라구요 아이도 재미있어 해요,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
1,아 그렇군요 무료체험 이것저것 해봤는데 솔직히 비교가 안되네요 일단 아들램이가 하...,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
2,저희도 체험하고 나서 지금 하고 있어요. 각자마다 장단점 있는거 같아요. 아이가 좋...,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
3,아 그렇군요 저도 지금 알아보고 있는데 탭만 받아서 하다보니 골고루 활용을 못해서...,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
4,저희애둘 일년째하고있어요 둘다알아서들잘해요 저두 만족하고있구요,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문

'저 하구 있는데 괜찮다라구요 아이도 재미있어 해요'

In [54]:
df.text = df.text.apply(lambda x : re.sub('[ㄱ-ㅎ]+', '', x))

In [55]:
# # 불용어 제거

# stop_words = ['아이', '거', '저','저희', '것', '감사', '게', '때', '년',
#  '맘', '애','원',  '제','듯', '만',
# '쪽지',  '정보', '댓글', '이번', '부분',  '걸로', '챗', '저흰', '답변','말씀'
# '건가요', '얼마', '요즘', '지금', '센터', '아들', '딸', '올해', '안녕', '그게', '사용', '오늘', '학모',
# '연락처', '때문', '일', '전', '둘', '번', '데', '개', '건', '하나', '둘', '등', '달', '월', '가지', '후', '걸', '꺼', '곳', '해요', '첨'
# '결국', '명', '외', '경우', '쪽', '뭐', '내년', '땐', '그거', '날', '이거', '동안', '테', '어디', '쥴', '사', '이게', '사랑', '다음', '채팅',
#  '무엇', '그때', '적', '당', '뒤', '거기', '문의', '여기', '이', '나', '반', '편', '대', '안', '건데', '눈', '문', '회',
# '그건', '인', '법', '위', '중', '넵', '주', '점', '기', '건지', '이것', '그것', '개월', '주세요', '주일']

# def stopwords_check(A):
#     text_list = []
#     if A not in stop_words:
#         text_list.append(A)

#     return text_list

# df['text_list'] = df['text'].apply(lambda x : stopwords_check(x))

In [56]:
df

,text,title,topic,yyyy,mm,etc
0,저 하구 있는데 괜찮다라구요 아이도 재미있어 해요,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
1,아 그렇군요 무료체험 이것저것 해봤는데 솔직히 비교가 안되네요 일단 아들램이가 하...,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
2,저희도 체험하고 나서 지금 하고 있어요. 각자마다 장단점 있는거 같아요. 아이가 좋...,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
3,아 그렇군요 저도 지금 알아보고 있는데 탭만 받아서 하다보니 골고루 활용을 못해서...,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
4,저희애둘 일년째하고있어요 둘다알아서들잘해요 저두 만족하고있구요,⚘밀크* 수업 하시는분 계실까요?,초등 밀크티,2022,2,본문
...,...,...,...,...,...,...
5630,저는 아들을 키우고있는엄마예요. 저는 지금까지 애들 사교육도 시켜본적없고 집에서...,사교육에대한생각,초등 밀크티,2022,1,댓글
5631,이번에 초등학교 들어가는 아이가 있는데 밀크티 체험해보고 싶어서요. 밀크티 하고 계...,밀크티 체험해보고 싶은데,초등 밀크티,2022,1,댓글
5632,지금까진 아무것도 안했는데 내년에 초등학교 간다생각하니 이제 뭐라도 시켜야 할것 같...,올해 7세 학습지,초등 밀크티,2022,1,댓글
5633,올해 아직 아무것도 몰음 초등 2학년 집에서 문제집 푸는정도 에요 홈소핑 보...,윙x 밀크x,초등 밀크티,2022,1,댓글
5634,초등학생 애들 밀크 무료체험 해보고싶은데 영사님 통해서 하는거랑 지인추천 받고하는...,밀크* 무료체험 해보고싶은데 도와주세요~~,초등 밀크티,2022,1,댓글